name: CD EventBridge Schedules - Sync

on:
  push:
    branches: [main]
    paths: ['eventbridge/cronogramas/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-schedules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Update EventBridge Schedules
        run: |
          for file in eventbridge/cronogramas/*.json; do
            [ -e "$file" ] || continue
            NAME=$(basename "$file" .json)
            echo "--- Atualizando Schedule: $NAME ---"
            
            # Higieniza os nulls do schedule
            jq 'del(..|nulls)' "$file" > clean.json
            
            # Falhará intencionalmente se o Schedule não existir (comportamento estrito de Update)
            aws scheduler update-schedule --name "$NAME" --cli-input-json "file://clean.json"
            
            rm clean.json
          done