name: CD EventBridge

on:
  push:
    branches: [main]
    paths: ['eventbridge/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      # Deploy de Rules
      - name: Sync Rules
        run: |
          for file in eventbridge/regras/*.json; do
            NAME=$(basename "$file" .json)
            RULE_JSON=$(jq -c '.Rule | .EventPattern = (.EventPattern | tojson)' "$file")
            TARGETS_JSON=$(jq -c '.Targets' "$file")
            aws events put-rule --cli-input-json "$RULE_JSON"
            aws events put-targets --rule "$NAME" --targets "$TARGETS_JSON"
          done

      # Deploy de Schedules
      - name: Sync Schedules
        run: |
          for file in eventbridge/cronogramas/*.json; do
            aws scheduler update-schedule --cli-input-json "file://$file"
          done