name: CD CD EventBridge Schedules - Sync

on:
  push:
    branches: [main]
    paths: ['eventbridge/cronogramas/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-schedules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Upsert EventBridge Schedules
        run: |
          set -euo pipefail
          
          for file in eventbridge/cronogramas/*.json; do
            [ -e "$file" ] || continue
            NAME=$(basename "$file" .json)
            echo "--- Sincronizando Schedule: $NAME ---"
            
            jq -c 'del(..|nulls)' "$file" > sched_cli.json
            
            # Checa silenciosamente se o Schedule existe
            if aws scheduler get-schedule --name "$NAME" > /dev/null 2>&1; then
              echo "Schedule existente encontrado. Aplicando Update..."
              aws scheduler update-schedule --name "$NAME" --cli-input-json file://sched_cli.json
            else
              echo "Schedule não encontrado. Aplicando Create..."
              aws scheduler create-schedule --name "$NAME" --cli-input-json file://sched_cli.json
            fi
            
            rm -f sched_cli.json
          done