name: CD Glue Jobs - Sync

on:
  push:
    branches: [main]
    paths: ['glue/jobs/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Update Glue Jobs and Tags
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION="us-east-2"

          for file in glue/jobs/*.json; do
            [ -e "$file" ] || continue
            NAME=$(jq -r '.JobName' "$file")
            echo "--- Atualizando Job: $NAME ---"
            
            # 1. Higieniza os nulos apenas do bloco de configuração (Isolamento de falhas)
            jq -c '.JobUpdate | del(..|nulls)' "$file" > update_payload.json
            
            # 2. Atualiza a infraestrutura do Job
            aws glue update-job --job-name "$NAME" --job-update "file://update_payload.json"
            
            # 3. Tratamento de Governança (Tags)
            # O jq 'length' verifica se o dicionário de tags não está vazio
            TAGS_COUNT=$(jq '.Tags | length' "$file")
            if [ "$TAGS_COUNT" -gt 0 ]; then
              echo "Aplicando Tags de Governança..."
              JOB_ARN="arn:aws:glue:${REGION}:${ACCOUNT_ID}:job/${NAME}"
              
              # Converte o dicionário JSON nativo para o formato Key=Value esperado pela CLI da AWS
              TAGS_STRING=$(jq -r '.Tags | to_entries | map("\(.key)=\(.value)") | join(",")' "$file")
              
              aws glue tag-resource --resource-arn "$JOB_ARN" --tags-to-add "$TAGS_STRING"
            fi
            
            rm update_payload.json
          done