name: CD Glue Scripts - Sync

on:
  push:
    branches: [main]
    paths: ['glue/scripts/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Sync Scripts to S3
        run: |
          echo "--- Sincronizando Scripts PySpark/Python ---"
          # O parâmetro --delete garante o GitOps: se você apagar o script no Git, ele apaga no S3
          # O parâmetro --exact-timestamps força a verificação rigorosa de modificação
          aws s3 sync ./glue/scripts/ s3://scripts-automacao-pedro/artifacts/scripts/ \
            --delete \
            --exact-timestamps \
            --exclude "*" \
            --include "*.py"