name: CD Glue Libs - Sync

on:
  push:
    branches: [main]
    paths: ['glue/libs/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Sync Libraries to S3
        run: |
          echo "--- Sincronizando Bibliotecas e Dependências (Wheels/Zips) ---"
          aws s3 sync ./glue/libs/ s3://scripts-automacao-pedro/artifacts/libs/ \
            --delete \
            --exact-timestamps \
            --exclude "*" \
            --include "*.whl" \
            --include "*.zip" \
            --include "*.jar"